root_file: "/Users/leonardoplini/Desktop/Visualizations/data_to_visualize/Prova5Feb26.root"
# root_file: "/Users/leonardoplini/Desktop/Visualizations/data_to_visualize/Ntupla-Transformer.root"
# root_file: "/Users/leonardoplini/Desktop/Visualizations/data_to_visualize/Ntupla-Develop.root"

visualizer: "Combined" # "Combined", "GTK"

event_number: 0
tree_path : "/SlimReco;1"
x_key: "GigaTracker/fHits/fHits.fPositionX"
y_key: "GigaTracker/fHits/fHits.fPositionY"
z_key: "GigaTracker/fHits/fHits.fPositionZ"
time_key: "GigaTracker/fHits/fHits.fTime"
KTAG_key: "EventHeader/fFineTime"
time_window_min: -10
time_window_max: 10
predicted_tracks_indexes: "/SlimReco;1/GigaTracker/fCandidates/fCandidates.fHitsIndexes"

# STRAW
straw_x1_key : "Spectrometer/fCandidates/fCandidates.fPositionXBeforeMagnet"
straw_y1_key : "Spectrometer/fCandidates/fCandidates.fPositionYBeforeMagnet"
straw_x_slope_key : "Spectrometer/fCandidates/fCandidates.fSlopeXBeforeMagnet"
straw_y_slope_key : "Spectrometer/fCandidates/fCandidates.fSlopeYBeforeMagnet"

plot_folder_path : "plots"
dataframe_path : "plots"