root_file: "data_to_visualize/Second_element_to_visualize.root"
tree_path : "/SlimReco;1"
x_key: "GigaTracker/fHits/fHits.fPositionX"
y_key: "GigaTracker/fHits/fHits.fPositionY"
z_key: "GigaTracker/fHits/fHits.fPositionZ"
time_key: "GigaTracker/fHits/fHits.fTime"
KTAG_key: "EventHeader/fFineTime"
time_window_min: -10
time_window_max: 10

transformer_threshold: 0.2
plot_folder_path : "plots"
dataframe_path : "plots"
